# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42b78ae3e88c373b69519103ab2789e11f14c9a1cf6b9ee833bded68d8b4e00e16799ccf3f9b17a30be23c6d6ed67499a5e2557eec154632d5cdedd8fcfab27

test:
  secret_key_base: 6615b922d06c1573c1eea1c99234814b5eeb89cc6c5032fa10e1271e2e796c93cf7b5d626fe550a5a4992ea90fb15dc54b1fe83f74cc2e958dec015d36ab76d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
